const r = require('express').Router();
const { authRequired } = require('../middleware/auth');
r.use(authRequired);
r.get('/me', (req, res, next) => require('../controllers/userController').me(req, res, next));
r.put('/me', (req, res, next) => require('../controllers/userController').updateMe(req, res, next));
r.get('/wishlist', (req, res, next) => require('../controllers/userController').wishlist(req, res, next));
r.post('/wishlist/:id', (req, res, next) => require('../controllers/userController').toggleWishlist(req, res, next));
r.get('/recent', (req, res, next) => require('../controllers/userController').recent(req, res, next));
r.post('/recent/:id', (req, res, next) => require('../controllers/userController').trackRecent(req, res, next));
r.get('/stats', (req, res, next) => require('../controllers/userController').dashboardStats(req, res, next));
module.exports = r;
